name: Build, Push and Deploy DS to DockerHub

on:
  workflow_dispatch:
  pull_request:
    branches: [main ]










env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  REPO_API: api-gateway
  REPO_CLIENT: client-service
  REPO_ACCOUNT: account-service

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build & Push API Gateway Docker image
        run: |
          cd ${{ env.REPO_API }}
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/api-gateway:latest .
          docker push ${{ env.DOCKERHUB_USERNAME }}/api-gateway:latest

      - name: Build & Push Client Service Docker image
        run: |
          cd ../${{ env.REPO_CLIENT }}
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/client-service:latest .
          docker push ${{ env.DOCKERHUB_USERNAME }}/client-service:latest

      - name: Build & Push Account Service Docker image
        run: |
          cd ../${{ env.REPO_ACCOUNT }}
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/account-service:latest .
          docker push ${{ env.DOCKERHUB_USERNAME }}/account-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Simulate Deployment
        run: echo " deployment"
