name: Build, Push and Deploy DS to DockerHub

on:
    push:
        branches:
          - main
    pull_request:
        types: [opened, reopened, edited]
        branches:
          - main
    workflow_dispatch:


env:
  # À compléter avec vos secrets DockerHub
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  REPO_API: api-gateway
  REPO_CLIENT: client-service
  REPO_ACCOUNT: account-service


jobs:

  build:
    name: Build and Push Images to DockerHub
    runs-on: ubuntu-latest
    steps:
      # Checkout code (à compléter)
      - name: Récupérer le code
        uses: actions/checkout@v4
# Installer Java (à compléter)
      - name: Installer Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      
      

      # Se connecter à DockerHub (à compléter)
      - name: Se connecter à DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build API Gateway (à compléter)
      - name: Build & Push API Gateway Image
        uses: docker/build-push-action@v5
        with:
          context: ./api-gateway
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.REPO_API }}:latest



      # working-directory: ds-api-gateway
      # run: |
      - name: Build & Push Client Service Image
        uses: docker/build-push-action@v5
        with:
          context: ./client-service
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.REPO_CLIENT }}:latest

      # Build Client Service (à compléter)
      # working-directory: ds-client-service
      # run: |
      - name: Build & Push Account Service Image
        uses: docker/build-push-action@v5
        with:
          context: ./account-service
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.REPO_ACCOUNT }}:latest

      # Build Account Service (à compléter)
      # working-directory: ds-account-service
      # run: |

  deploy:
    
    name: Deploy All Services
    runs-on: ubuntu-latest
    # définir la dépendance avec le job build
    needs: build
    steps:
      - name: Simulate deployment
        run: echo "Simulating deployment of all services"|